// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppMLPACK.h>
#include <Rcpp.h>

using namespace Rcpp;

// log_reg
arma::vec log_reg(arma::mat X, arma::vec y);
RcppExport SEXP _panning2_log_reg(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(log_reg(X, y));
    return rcpp_result_gen;
END_RCPP
}
// pred_log_reg
arma::vec pred_log_reg(arma::mat X, arma::vec y, arma::mat X_new);
RcppExport SEXP _panning2_pred_log_reg(SEXP XSEXP, SEXP ySEXP, SEXP X_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_new(X_newSEXP);
    rcpp_result_gen = Rcpp::wrap(pred_log_reg(X, y, X_new));
    return rcpp_result_gen;
END_RCPP
}
// cross_validation_logistic
double cross_validation_logistic(arma::mat& X, arma::vec& y, unsigned int K, unsigned int M);
RcppExport SEXP _panning2_cross_validation_logistic(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type K(KSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(cross_validation_logistic(X, y, K, M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_panning2_log_reg", (DL_FUNC) &_panning2_log_reg, 2},
    {"_panning2_pred_log_reg", (DL_FUNC) &_panning2_pred_log_reg, 3},
    {"_panning2_cross_validation_logistic", (DL_FUNC) &_panning2_cross_validation_logistic, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_panning2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
