# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_reg <- function(X, y) {
    .Call('_panning2_log_reg', PACKAGE = 'panning2', X, y)
}

pred_log_reg <- function(X, y, X_new) {
    .Call('_panning2_pred_log_reg', PACKAGE = 'panning2', X, y, X_new)
}

cross_validation_logistic <- function(X, y, K, M) {
    .Call('_panning2_cross_validation_logistic', PACKAGE = 'panning2', X, y, K, M)
}

