# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Logistic regression
#'
#'@param X a p x n matrix of regressor
#'@param y a n x 1 vector of response
#'@export
log_reg <- function(X, y) {
    .Call('_panning2_log_reg', PACKAGE = 'panning2', X, y)
}

#'Prediction of logistic regression
#'
#'@param X a p x n matrix of regressor
#'@param y a n x 1 vector of response
#'@param X_new a p x m matrix of new regressor
#'@export
pred_log_reg <- function(X, y, X_new) {
    .Call('_panning2_pred_log_reg', PACKAGE = 'panning2', X, y, X_new)
}

#'Cross-validation for logistic regression
#'
#'@param X a p x n matrix of regressor
#'@param y a n x 1 vector of response
#'@param K number of splits
#'@param M number of repetitions
#'@export
cross_validation_logistic <- function(X, y, K, M) {
    .Call('_panning2_cross_validation_logistic', PACKAGE = 'panning2', X, y, K, M)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_panning2_RcppExport_registerCCallable', PACKAGE = 'panning2')
})
